### ISSUE TITLE
[Question] Doesn't state machine break godot's best practice rules?

### ISSUE THREAD

**Issue by scriptsengineer** [gdquest-demos/godot-design-patterns#3]
Doesn't state machine break godot's best practice rules? 
Each state has a reference to the parent "state machine", shouldn't it be the parent that should only have a reference to the children? and if the children want to communicate it could be through signs.

- Why?
Could these states be used in other types of state machine other than this dependency

**Comment by NathanLovato** [comment]
In short, no, not really, that's the state pattern for you: the state object takes control of the "host." It's similar to how a script takes control of a node it's attached to, it's the same kind of relationship.

What people call "best practices" are general guidelines, not rules. In code, you want to solve problems pragmatically. In some cases the state pattern is a pragmatic solution, it solves actual problems you have managing the different behaviors of an entity, so it makes sense to use it.

Implementation details like having nodes take control of their owner or having an object take control of another inside of scripts don't matter too much. Often it's the same result: states are relatively coupled with their host.

You could decouple them a bit using signals but:

- This pattern generally is often about writing very specific states for very specific entities (the player's jump state, attack state, etc.), so it makes sense for the code to be coupled.
- If you use only signals for communication, you're going to make your code longer and more indirect, making it harder to read, write, and maintain.
- If you really want, you can use guard conditions to get the same concrete effects as signals: avoiding errors.

All in all, you should test the pattern in different situations, test alternative code, and do your best to assess the tradeoffs each approach requires. Code structure and design patterns are all about tradeoffs.

I hope this helps!

**Comment by scriptsengineer** [comment]
Thank you very much for the answer, I like to follow the practices because they end up avoiding future problems, which usually costs more maintenance time than creation.
I really understand about being pragmatic, especially about using states.
